# madlib.yml
on: issues
name: Create a MadLibs in GitHub Issues
jobs:
  madlib:
    name: markdown-marker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bdougie/variables-in-markdown@v1.0.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
