name: Push all PR
on: 
  pull_request:
  push:
    branches: 
      - master
      - dev
jobs: 
  tests:
    name: Running unittests
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use nodejs ${{matrix.node-version }}
        uses: actions/setup@v1 
        with: 
         node-version: ${{matrix.node-version }}
      - name: npm install, run and test
        run: |
          npm run build --if-present
          npm test
#        env:
#          CI: true 
